### PR TITLE
Custom AmazonKeyspaces to retry on same host

### PR DESCRIPTION
**Pull request by Rathan8**
*Issue #, if available:* retry on same host rather than next host

*Description of changes:*Custom AmazonKeyspaces to retry on same host for nodejs driver

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by nwheeler81 — COMMENTED** [review]
Add the lic header (MIT or Apache 2.0)

**Review by michaelraney — APPROVED** [review]
Looks good!

**Comment by Rathan8** [comment]
@michaelraney @nwheeler81 also added exponential retry and unit test cases for retry policies please review and merge

**Comment by nwheeler81** [comment]
looks good

**Pull request merged**
